file_format: "1"
id: kuniboard
name: Kuniboard
type: shield
url: https://github.com/tobiasarndt/Kuniboard
requires: [seeeduino_xiao_ble]
features:
    - keys
siblings:
    - kuniboard_left
    - kuniboard_right